# These are supported funding model platforms

github: safi-ullah-031 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: safi.ullah.031 # Replace with a single Buy Me a Coffee username
thanks_dev: safi-ullah-031 # Replace with a single thanks.dev username
